Repository wafflestudio20-5/team4-server, pull requests merged in 2023-02, with the labels that each got.

#53 Fix: GET, POST, PUT, DELETE /api/user/me/reviews 코드 리팩토링
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/InquiryRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/UserController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/DeleteReviewRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/ReviewRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
Labels: documentation

#61 팔로우 & 유저 검색 API 구현
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/MemoryDB.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/FollowEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/FollowRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/service/StyleService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/UserController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/response/FollowsResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/response/UserSearchResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/domain/User.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
Labels: bug, documentation, enhancement

#62 api/user/search 수정
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/response/FollowsResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/response/UserResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/response/UserSearchResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
Labels: documentation

#55 Feat: POST /api/style/:styleId/like
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/StyleController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/request/PostStyleRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/StyleEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/UserLikedStyleEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/service/StyleService.kt
Labels: enhancement

#52 Feat: POST, PUT, DELETE /api/user/me/comment
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/CommentEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/api/ItemController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/StyleController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/UserLikedStyleEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/service/StyleService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/UserController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/PostCommentRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/PutCommentRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
Labels: documentation, enhancement

#60 Feat: PATCH, DELETE /api/style/:styleId
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/MemoryDB.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/StyleController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/request/PatchStyleRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/StyleEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/service/StyleService.kt
Labels: documentation, enhancement

#67 회의에서 나왔던 내용 수정
  src/main/kotlin/com/wafflestudio/toyproject/team4/common/CustomExceptionHandler.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/api/CommentController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/CommentEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/InquiryEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/InquiryRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/domain/Comment.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/service/ReviewService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/service/ItemService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/purchase/database/CartItemEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/purchase/database/PurchaseEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/purchase/service/PurchaseService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/StyleController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/ItemStyleEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/StyleEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/StyleRepositories.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/UserLikedStyleEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/service/StyleService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/FollowEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/RecentItemEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserRepository.kt
  src/main/resources/application.yaml
Labels: bug

#68 Fix: GET Style , DELETE Review 코드 변경
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/service/ReviewService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/purchase/database/PurchaseEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/service/StyleService.kt
Labels: bug
