Repository wafflestudio20-5/team4-server, pull requests merged in 2023-01, with the labels that each got.

#2 Add api/auth/register
  src/main/kotlin/com/wafflestudio/toyproject/team4/config/AuthConfig.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/AuthController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/RegisterRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthService.kt
Labels: enhancement

#3 Add api/auth
  docker-compose.yml
  src/main/kotlin/com/wafflestudio/toyproject/team4/common/Annotations.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/common/CustomExceptionHandler.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/common/Exceptions.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/common/QueryDslConfig.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/config/WebConfig.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/AuthController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/LoginRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/NicknameRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/UsernameRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/response/AuthToken.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/response/NicknameResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/response/UsernameResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/domain/User.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthProperties.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthTokenService.kt
  src/main/resources/application.yaml
Labels: documentation, enhancement

#4 Add api/items
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/api/ItemController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/api/request/ItemRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/api/response/ItemRankingResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/OptionEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/OptionRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/domain/Item.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/service/ItemService.kt
Labels: enhancement

#7 소셜 로그인 for Kakao 구현
  build.gradle.kts
  src/main/kotlin/com/wafflestudio/toyproject/team4/config/AuthConfig.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/domain/User.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthTokenService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/oauth/entity/ProviderType.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/oauth/handler/OAuth2AuthenticationSuccessHandler.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/oauth/info/OAuth2UserInfo.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/oauth/info/OAuth2UserInfoFactory.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/oauth/info/impl/KakaoOAuth2UserInfo.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/oauth/service/CustomOAuth2UserService.kt
  src/main/resources/application.yaml
Labels: enhancement

#24 Add api/image-upload
  build.gradle.kts
  src/main/kotlin/com/wafflestudio/toyproject/team4/common/CustomExceptionHandler.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/common/Exceptions.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/image/CloudinaryProperties.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/image/api/ImageController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/image/api/response/ImageUploadResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/image/service/ImageService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/AuthController.kt
  src/main/resources/application.yaml
Labels: documentation, enhancement

#30 Add GET /api/search
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/api/ItemController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/api/request/ItemRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/domain/Item.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/service/ItemService.kt
Labels: enhancement

#32 Add api/user/me/shopping-cart
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/image/service/ImageService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/UserController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/PatchShoppingCartRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/PostShoppingCartRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/CartItemEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
Labels: documentation, enhancement

#35 Add POST /api/user/me/recently-viewed
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/UserController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/RecentlyViewedRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/RecentItemRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
Labels: enhancement

#31 Add /api/item/:id/reviews
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/api/response/InquiriesResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/api/response/ReviewsResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/CommentEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/CommentRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/InquiryEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/InquiryImageEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/InquiryRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewImageEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewImageRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/domain/Comment.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/domain/Inquiry.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/domain/Review.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/api/ItemController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemImageEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemImageRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/domain/Item.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/service/ItemService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/response/ReviewsResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/PurchaseEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/ReviewRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
Labels: enhancement

#36 Add GET, PUT, DELETE /api/user/me/item-inquiries
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/InquiryEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/InquiryImageRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/InquiryRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/UserController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/PutItemInquiriesRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
Labels: enhancement

#39 Add /api/auth/social-login
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/AuthController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthTokenService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/oauth/handler/OAuth2AuthenticationSuccessHandler.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/oauth/info/OAuth2UserInfoFactory.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/oauth/service/CustomOAuth2UserService.kt
Labels: bug, documentation, enhancement

#40 Add POST /api/item/:id/inquiry
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/domain/Inquiry.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/api/ItemController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/api/request/PostItemInquiryRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/service/ItemService.kt
Labels: documentation, enhancement

#41 HTTPS 배포
  src/main/kotlin/com/wafflestudio/toyproject/team4/config/WebConfig.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/oauth/handler/OAuth2AuthenticationSuccessHandler.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/oauth/service/RedirectUrlProperties.kt
  src/main/resources/application.yaml
Labels: enhancement

#45 Add GET /api/styles, & /api/style/:styleId, POST /api/style
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemImageRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/MemoryDB.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/domain/RankingItem.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/service/ItemService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/PostStyleRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/StyleController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/response/StyleResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/response/StylesResponse.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/FollowEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/FollowRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/ItemStyleEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/StyleEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/StyleRepositories.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/database/UserLikedStyleEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/domain/Style.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/service/StyleService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/domain/User.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
Labels: documentation, enhancement

#57 Feat: Patch api/user/me
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/image/api/ImageController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/MemoryDB.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/AuthController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/UserController.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/PasswordRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/PatchMeRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/RegisterRequest.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/domain/User.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthService.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
Labels: documentation, enhancement

#54 Fix: GET, POST purchase 와 GET shoppingCart 코드 리팩토링
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserRepository.kt
  src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
Labels: documentation
